### ISSUE TITLE
Parameter analysis POST requests

### ISSUE THREAD

**Issue by Hipapheralkus** [JGillam/burp-paramalyzer#11]
regular POST parameters are not shown in the Analysis. Fore example, neither password, not userid is shown:
![image](https://user-images.githubusercontent.com/4717664/47720034-3d124480-dc4d-11e8-9128-ee7e09eb0691.png)
I would like to see all the userid parameter values which are used, but there are no such entries.

**Comment by JGillam** [comment]
That's odd.  Paramalyzer pulls its interpretation of input parameters directly from Burp Suite's API, so it should be seeing those.  I will investigate.

**Comment by JGillam** [comment]
@Hipapheralkus I'm not seeing this issue on the BAppStore version of Paramalyzer.  Please check that the Target --> Scope tab has rules that are inclusive for this request.  

One way to know for certain is if you right-click on that request, if you see the option to "Remove from Scope" then it is already considered in scope and will be processed by Paramalyzer.  But if you see the option to "Add to Scope", then Paramalyzer will not process that request.

Let me know if it is in scope and I will investigate further.
