### ISSUE TITLE
Keep the BAppStore version in sync

### ISSUE THREAD

**Issue by ngregoire** [JGillam/burp-paramalyzer#19]
Hello,

the BAppStore currently hosts v2.0 of the extension (last update: 14 January 2019). That means that most users will miss both the features introduced in v2.1.0 (REST + JSON) and the few fixes pushed afterwards. From my understanding of the BAppStore update process, only pull requests from the original author (and original repository) will be accepted.

In order to have both versions in sync, could you please create a PR from your current version to Portswigger's one, then notify support@portswigger.net by email so that they can review it?

Thanks in advance!

**Comment by JGillam** [comment]
I plan to.  I went down a path with developing some additional functionality after 2.0 that I have decided to change direction on somewhat, so I am shifting a lot around.  Once I get things stable again I plan to push out a BAppStore update.
