### ISSUE TITLE
Cookies tab doesn't honor the defined scope

### ISSUE THREAD

**Issue by ngregoire** [JGillam/burp-paramalyzer#20]
Hello,

the "Cookies" tab will list all cookies stored in the Proxy History, even if the corresponding messages aren't in scope. The bug is in method firstPass(), where isInScope() is checked only for parameters.

    private void firstPass(IExtensionHelpers helpers, IHttpRequestResponse[] messages) {
            [...]
            //  Analyze response for cookies
            if(messages[i].getResponse() != null) {
                IResponseInfo responseInfo = helpers.analyzeResponse(messages[i].getResponse());
                List<String> headers = responseInfo.getHeaders();
                for (String header: headers){
                    if (startsWithIgnoreCase(header, "set-cookie:")) {
                        processCookieHeader(header);
                    }
                }
            }
            [...]

**Comment by JGillam** [comment]
I believe this was resolved in v 2.2.2 but I forgot to close this issue.
